name: Nightly build

on:
  schedule:
    # 23:30 UTC, 0:30 or 1:30 CET/CEST
    - cron: "30 23 * * *"
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare build environment
    runs-on: ubuntu-latest
    outputs:
      hasNewChanges: ${{ steps.nightly.outputs.hasNewChanges }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          clean: false
      - name: Set executable permissions to gradlew
        run: chmod +x ./gradlew
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install packages
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            python-dotenv
            pycryptodome
            mysql-connector-python
            requests
  build:
    name: Build APK
    runs-on: self-hosted
    needs:
      - prepare
    if: ${{ needs.prepare.outputs.hasNewChanges == 'true' }}
    outputs:
      androidHome: ${{ env.ANDROID_HOME }}
      androidSdkRoot: ${{ env.ANDROID_SDK_ROOT }}
    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Clean build artifacts
        run: |
          rm -rf app/release/*
          rm -rf app/build/outputs/apk/*
          rm -rf app/build/outputs/bundle/*
      - name: Assemble official release with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleOfficialRelease
